### ISSUE TITLE
Service Worker how-to

### ISSUE THREAD

**Issue by emaildano** [xwp/pwa-wp#112]
Hey!

From the README it sounds like service workers at this point at not automatically generated/added to sites due to how service workers operate. e.g. Multiple service workers can create a few issues because there can/should only be one.

1. Is that assumption correct?
2. If so, do we have to add that script to our sites on a case by case basis to enable the SW?

I may be reading this wrong but it sounds like until Core has support for SWs this will be a manual step for now. At least with this plugin.

**Comment by westonruter** [comment]
Actually, a service worker _are_ automatically added to sites. The thing is that only _one_ service worker is registered for the frontend of the site (and one for the admin). Themes and plugins then hook into the generation of the service worker to add their logic. This means they can avoid attempting (and failing) to register multiple service workers, because the feature plugin registers them on their behalf.
