### ISSUE TITLE
Offline template misleading when server is down

### ISSUE THREAD

**Issue by iandunn** [xwp/pwa-wp#177]
1. Visit `wp-admin` so that service worker is installed
1. Stop nginx
1. Refresh

You'll see:

> You seem to be offline.
> 
> Please check your internet connection. In the future, this error screen could provide you with actions you can perform while offline, like edit recent drafts in Gutenberg.

That's misleading, because it makes the user think the problem is on their end, rather than the server's.

Off the top of my head, I'm not sure if it's practical to try and detect the difference, but I figured I'd mention it. I guess the browser could attempt an `OPTIONS` HTTP request to `wordpress.org` or something, as a quick way to test if the user is actually offline.

**Comment by westonruter** [comment]
Humm. I should think rather that an error template should be used here rather than the offline template. I presume the admin request is returning with a `0` status code?

**Comment by iandunn** [comment]
It's `200` for me.

<img width="1214" alt="Screen Shot 2019-06-27 at 4 36 55 PM" src="https://user-images.githubusercontent.com/484068/60307542-f10dc180-98f9-11e9-9f46-a69c7c1ec4c1.png">

&nbsp;

<img width="1215" alt="Screen Shot 2019-06-27 at 4 37 32 PM" src="https://user-images.githubusercontent.com/484068/60307543-f10dc180-98f9-11e9-9284-44e773aeb2fc.png">

**Comment by westonruter** [comment]
OK, I suppose this makes sense given how it is architected right now. When a `fetch()` fails due to the server not responding, there is no difference between whether you are offline or the server is offline.

So I think the simple fix is to check for `navigator.onLine` when the request fails. If it is `true` then we know it is actually the server that is offline (probably) and we can show a message related to that; otherwise, if it is `false` then we know the user is offline and we can show the same message as we do presently.

**Comment by westonruter** [comment]
Proposed fix in #190.
