### ISSUE TITLE
VM3 admin-ajax.php:1 Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by Stanzilla** [xwp/pwa-wp#315]
Only getting this when the PWA plugin is enabled

```VM29179 plugins.php:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://learn.coregames.com/wp-admin/') with script ('https://learn.coregames.com/wp-admin/admin-ajax.php?action=wp_service_worker'): ServiceWorker script evaluation failed```

assume this might be fixed with the future work of making a separate SW for the admin panel but wanted to report it anyway

**Comment by westonruter** [comment]
Can you share the full output of the service worker script, like in a Gist? You may be experiencing this issue: https://github.com/GoogleChromeLabs/pwa-wp/issues/293

**Comment by Stanzilla** [comment]
Yup, here you go https://gist.github.com/Stanzilla/7b65f9305f4b0e9df30b0c2773e0b9c0

**Comment by westonruter** [comment]
OK, yeah. See the `<style class="astra-menu-appearance-style">...</style>`? That's a bug in Astra where the theme is incorrectly printing styles at `wp_enqueue_scripts` (or `admin_enqueue_scripts`) rather than strictly enqueueing scripts/styles. They should rather be using the `wp_print_styles` action (or equivalent admin action). So first I recommend reporting this as a bug to Astra, but the PWA plugin will also prevent this from happening in #293.

**Comment by Stanzilla** [comment]
Awesome, thank you!
