### ISSUE TITLE
How to use the plugin

### ISSUE THREAD

**Issue by Micu22** [xwp/pwa-wp#421]
Main question: Is there a list of all methods for configuring the service worker that can be used in a custom theme?
I have difficulties finding info on how this plugin works.
The manifest works fine, but there are some other strange things happening.
Currently it generates this code:
```
if ( navigator.serviceWorker ) {
	window.addEventListener( 'load', function() {
		{
			navigator.serviceWorker.register(
				"http:\/\/localhost\/app\/wp.serviceworker",
				{"scope":"\/app\/"}
			).then( reg => {

			} );
		}
		{
			navigator.serviceWorker.register(
				"http:\/\/localhost\/app\/wp-admin\/admin-ajax.php?action=wp_service_worker",
				{"scope":"\/app\/wp-admin\/"}
			).then( reg => {
				document.cookie = "wordpress_sw_installed=1; path=\/app\/wp-admin\/; expires=Fri, 31 Dec 9999 23:59:59 GMT; secure; samesite=strict";
			} );
		}
	} );
}
```
but localhost/app/wp.serviceworker returns error 404, how can I create this file?
Also the service worker is registered multiple times...
How can I help finish this plugin and merge it with wp core?

**Comment by westonruter** [comment]
How you seen the wiki documentation? https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker

As for the 404, this seems to be due to you not having pretty permalinks enabled, although when that happens it's supposed to use a query var instead:

https://github.com/GoogleChromeLabs/pwa-wp/blob/e028bc0153a406994673c557459aec7e22a99eee/wp-includes/service-workers.php#L97-L105

The service worker script is not an actual file on the filesystem. It is served by WordPress in the same way `robots.txt` is served by WP.

**Comment by Micu22** [comment]
Thank you pretty permalinks have solved the issue.
Regarding the wiki, yes I have read it, but service workers, in general, are not WordPress' programmer expertise so expanding the wiki with more code and more explanations would help a lot.
What are the current expectations on whether this plugin will be merged with wp core?

**Comment by westonruter** [comment]
> Thank you pretty permalinks have solved the issue.

You enabled pretty permalinks and it fixed the problem? That's strange because it shouldn't have been using `/wp.serviceworker` if pretty permalinks weren't enabled in the first place. It should have instead been returning `/?wp_service_worker=1`.

> Regarding the wiki, yes I have read it, but service workers, in general, are not WordPress' programmer expertise so expanding the wiki with more code and more explanations would help a lot.

I just updated the service worker wiki page with some [more documentation](https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker#caching). The new offline browsing filters are intended to be the primary way you customize how the plugin behaves. You can go a level below and register your own caching routes, and and since,the PWA plugin's API is an abstraction of Workbox.js, you can refer to the [Workbox.js documentation](https://developers.google.com/web/tools/workbox).

> What are the current expectations on whether this plugin will be merged with wp core?

I don't know. Maybe in WP 5.8 or 5.9? I need to get more circulation among core contributors and do a formal proposal.

**Comment by Micu22** [comment]
I tested it again and I found what was causing the issue. I had .htaccess disabled, and my links had /index.php/ in them. Now with .htaccess enabled and pretty permalinks disabled it serves the service worker with '?wp_service_worker=1'
Thank you.
