### ISSUE TITLE
The service worker navigation preload error in Chrome

### ISSUE THREAD

**Issue by vralle** [xwp/pwa-wp#440]
Hi!
When browsing the site pages with PWA. error message in Chrome v89.0.4389.72: `The service worker navigation preload request failed with network error: net::ERR_INTERNET_DISCONNECTED`.
debug log:
```
workbox Using NetworkFirst to respond to '/'
logger.js:44 Unable to get a response from the network. Will respond with a cached response.
logger.js:44 Found a cached response in the 'wp-/-navigations' cache.
```

I'm not sure, but it might have something to do with new default Referrer-Policy for Chrome: strict-origin-when-cross-origin
The error appeared recently. The error does not change in any way depending on the referral policy of the site. I don't know what else can be done.

Some error in MS Edge v89.0.774.48.
FF v86 - no Error message.

**Comment by westonruter** [comment]
Thanks, I'm seeing this issue as well. I'm making an inquiry with the Workbox team.

**Comment by Stanzilla** [comment]
This will be fixed by upgrading Workbox to 6.1.2.

**Comment by westonruter** [comment]
@Stanzilla Thanks for that. I'm investigating to see exactly why that is. In the meantime, @vralle can you test with #443 to see if if fixes the issue for you as well? I was holding off on the update to v6 until I had more time to test for regressions and make updates for the breaking changes, but it's clear I'll need to not delay.

**Comment by westonruter** [comment]
Workbox v6.2.1 was updated to include https://github.com/GoogleChrome/workbox/issues/2749 which reduces the error logging due to a change in Chrome 89 for [offline detection](https://developer.chrome.com/blog/improved-pwa-offline-detection/). Nevertheless, this change doesn't seem to always apply to the PWA plugin because we enable navigation preload, and thus I still see the error coming from DevTools:

![image](https://user-images.githubusercontent.com/134745/111364829-f58a8880-864e-11eb-908e-c28f30f0a8d2.png)

In any case, I'm not actually seeing this causing a problem. The pages I navigate to are still saved to cache and when I go offline I can still navigate to them.

@vralle Aside from the error appearing in the console, were you noticing any regressions in offline browsing? 

This may just be something that Chrome DevTools needs to improve in its messaging for offline detection.

**Comment by vralle** [comment]
> Aside from the error appearing in the console, were you noticing any regressions in offline browsing?

I confirm that the pages are cached and available offline.

https://github.com/GoogleChrome/workbox/issues/2749#issuecomment-789792779

If I understood the comments correctly, the error message does not affect how SW works. They can be ignored.
