### ISSUE TITLE
Add reliable method for detecting HTTPS support

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#6]
The `is_ssl()` function is woefully inadequate to determine whether WordPress is being served via HTTPS. It is not reliable because HTTPS termination may be happening at a proxy and not at the server running WordPress. So it is not reliable to look at the server environment to determine if HTTPS is being served or is able to be served.

I believe the best way to detect HTTPS support is to actually perform a loopback request onto the home URL of the site with HTTPS and check that it responds properly with `sslverify` enabled. For added resilience, the request should include a token which the response then hashes with a secret which can then be compared to confirm that in fact it is the same WordPress install itself that is responding, and not some other WordPress site that is configured on HTTPS.

Once the HTTPS check is performed, the result should be stored in an option, and the option can then be checked instead of `is_ssl()`.

This would allow for a site to make use of HTTPS exclusively without manually adding a `FORCE_SSL_ADMIN` constant.

**Comment by gravityrail** [comment]
In addition, we should provide some kind of fail-safe if SSL configuration goes bad.

Imagine, for example, the user has wp-admin configured to redirect to `https`, however the certificate expires. In order to browse wp-admin without being redirected to a broken https page, they need to change a setting in wp-admin, but they can't use wp-admin...

One way of fixing this might be to have a wp-cron job which periodically detects if the https configuration is still valid, and if not it disables features that depend on https and shows a loud notice in wp-admin telling the user to fix SSL.

**Comment by westonruter** [comment]
As we chatted over DM, we'll need to make sure that `wp-cron.php` loopback requests always use HTTP and not HTTPS because otherwise cron could break if HTTPS becomes broken. This would be irrelevant if system cron is being used (and `DISABLE_WP_CRON`). We could simply filter `cron_request` to make sure that the `url` is HTTP and/or that `sslverify` is `false`.

**Comment by kienstra** [comment]
**Request To Work On This**

Hi @westonruter, 
Could I work on this? Thanks for the outline of the solution above.

**Comment by westonruter** [comment]
_Onwards!_

**Comment by postphotos** [comment]
Hi @kienstra, after peeking at your prototype in #16 I wanted to raise an idea here. I also mentioned parts of it in #17 and #18 about how HTTPS switchovers have been handled and the risks to not doing it correctly. Having done a ton of these by hand, I'm happy to talk this through.

I'd extend this issue to not only being about a method for detecting HTTPS support, but also, at the least, a base reason to explain to the user why they _wouldn't_ be supported.

I think your PR in #16 is well-scoped, I'd love to keep this issue open for discussion around HTTPS error catching to provide both a) deeper analysis of why a site breaks or isn't HTTPS ready, and b) a contextual interface summarizing that and how to fix it. 

Typically, similar to our conversations with AMP, these can be as simple as a hardcoded `http` in a CDN/file listing or an out-of-date plugin: Some kind of response explaining why instead of simply saying "this is broken" means that one pain point becomes way easier.

As you work on this, let me know if you have any ideas here!
