### ISSUE TITLE
Prototype an API to register service workers

### ISSUE THREAD

**Issue by postphotos** [xwp/pwa-wp#7]
As a developer, I should have a discrete way to register service workers to allow my plugin (or theme) to leverage a common approach that allows for collaborative integration features.

AC1: Create documentation based on what we think the API should look like, anticipating its evolution through the project.
AC2: Based on the work we're doing in #1, demo a service worker integration that allow for other tools to also register in our common framework.

**Comment by kienstra** [comment]
**Trac Ticket**

Maybe Weston's suggestion in this [trac ticket](https://core.trac.wordpress.org/ticket/36995) could be the basis of this API.

**Comment by westonruter** [comment]
I think my suggestion should be evaluated against [Mozilla's SW plugin](https://github.com/mozilla/wp-sw-manager).

**Comment by miina** [comment]
Looked into the Mozilla's Plugin (MP).

The idea behind the logic of the MP seems to be quite similar. Service Workers are registered by scope and then the SW logic put together into one based on the scope.

Some differences:
- Instead of using JS files per each SW a method with the logic for SW is created using PHP. The outputs of all methods per scope are concatenated into one. A sample registering for a SW via MP for caching assets:
```
Mozilla\WP_SW_Manager::get_manager()->sw()->add_content( 'write_sw' );

function write_sw() {
	?>
    var CACHE_NAME = 'my-cache';
    var urlsToCache = [
        'https://vvv.test/pwa/wp-content/themes/twentyseventeen/style.css',
    ];

    self.addEventListener('install', function(event) {
        // Perform install steps
        event.waitUntil(
        caches.open(CACHE_NAME)
            .then(function(cache) {
                console.log('Opened cache');
                return cache.addAll(urlsToCache);
            })
        );
    });
    self.addEventListener('fetch', function(event) {
        event.respondWith(
        caches.match(event.request)
            .then(function(response) {
                // Cache hit - return response
                if (response) {
            return response;
            }
            return fetch(event.request);
        }
    )
    );
    });
    <?php
}
```
Feels like having separate files per SW as @westonruter suggested is a cleaner/more structured way to go.

- Getting the SW-s per scope seems to be solved by actions, copied:
```
const ACTION = 'wpswmgr_serve';
add_action('wp_ajax_'. self::ACTION, array($this, 'parse_request'));
add_action('wp_ajax_nopriv_' . self::ACTION, array($this, 'parse_request'));
```
And the registered full path URL's for the SW looks like something this:
`.../wp-admin.php?action=wpswmgr_serve&_wpswmanager=' . urlencode($route);` where `$route` is the code name for scope. So basically when the action is triggered and `parse_request` method runs then based on `$_GET['_wpswmanager']` the methods registered for this scope are merged together.

This could be an alternative to using ` WP_Rewrite`.

Thoughts?

**Comment by westonruter** [comment]
I think that using `admin-ajax.php` for this is somewhat a vestige of WordPress's past which we should get away from, at least for a frontend context. Something very important to factor into the reasoning about the service worker URL is that _the service worker script must be loaded from the same origin as the host document._ This is critical to factor into cases where the home URL is not the same as the site URL, such as is the case on WordPress.com (htttps://example.com on frontend, and https://example.wordpress.com for the admin). So in order to successfully register service workers in the frontend and backend we need to make sure we have two routes, respectively. It is possible to access `admin-ajax.php` from the frontend, but some locked-down environments prevent accessing anything under `/wp-admin/` if you don't have a whitelisted IP. So I think that isn't a good approach.

> Feels like having separate files per SW as @westonruter suggested is a cleaner/more structured way to go.

Actually I don't think I suggested this. My suggestion for registering a service worker is like:

```php
wp_register_service_worker( 'foo-front', plugin_dir_path( __FILE__ ) . 'js/front-sw.js', array(), '/' );
```

Whereas in the Mozilla plugin, their approach is:

```php
$swmgr->sw()->add_content( 'some_function_that_prints_js_from_php' );
```

In both cases, the scripts would get concatenated and served from a single endpoint that would reference the desired scope. I like the `wp_register_service_worker()` approach because it is similar to the existing `WP_Scripts` API and it encourages the use of static JS files. The Mozilla approach is more similar to doing calls to `wp_add_inline_script()`. The ability to add dynamically-generated JS code to a service worker may very well be a valid use case, but I should think in general that the JS that is added to a service worker should be static. Otherwise, if dynamic then the service worker would potentially need to constantly need to get re-installed.

But what is the ideal route to use for the service worker in WP? Using the REST API doesn't make much sense since it is returning JavaScript not JSON. For the frontend we could have a route like:

```
https://example.com/?wp_service_worker=/
```

This could be beautified with WP_Rewrite like:

```
https://example.com/wp-service-worker.js?scope=/
```

_But_ I think this could be perilous in case of reverse proxies that could aggressively cache JS files. Since cache-busting query parameters are not used for service workers, this could cause the reverse proxy to hold onto the file indefinitely. So either we need to serve this with `Cache-Control: no-cache` or we would need to make sure that the endpoint is served with `Cache-Control: must-revalidate`. We'll should make sure that the service worker gets served with an `ETag` based on the hash of the concatenated contents, and then make sure that the endpoint serves an `If-None-Match` so that it can serve a `304 Not Modified` response. 

In the admin, we have to use `site_url()` (or `admin_url()`) as opposed to the `home_url()`. Note that the same `scope`-resolution logic used in JS should be ported to PHP. In the client, the selected scope is the one that has the longest match with the current path. So in the case of PHP, the `scope` param on the generated URL should likewise be the registered `scope` that has the longest match with the current `REQUEST_URI`. In other words, if I register a service worker with scope `/` then it would get served in both frontend and backend contexts, but if I register a service worker script with scope `/wp-admin/` then it would alone get served when accessing the page located at `/wp-admin/customize.php`

**Comment by miina** [comment]
> Feels like having separate files per SW as @westonruter suggested is a cleaner/more structured way to go.

What I meant here was that the suggested solution in https://core.trac.wordpress.org/ticket/36995 having static files per SW feels like a cleaner/more structured way compared to the Mozilla Plugin's approach.

> So either we need to serve this with Cache-Control: no-cache or we would need to make sure that the endpoint is served with Cache-Control: must-revalidate.

Also read about the `updateViaCache` option used within registering a Service Worker, if I understood correctly this should disable caching for the Service Worker file (by default?):
```
if ( 'serviceWorker' in navigator ) {
  navigator.serviceWorker.register( '/service-worker.js', {
    updateViaCache: 'import', // Default value. 
    scope: '...'
  } );
}
```
Not sure if it's applicable here, also as far as I understood it's not supported by older browser versions meaning that using `Cache-Control: max-age=0` (or sth similar) would be needed anyway.

**Comment by westonruter** [comment]
> Not sure if it's applicable here, also as far as I understood it's not supported by older browser versions

True, but I'm primarily thinking of reverse proxies here, not browsers. We would want to prevent, for example Akamai, from aggressively holding onto a `service-worker.js` file. Reverse proxies should be forbidden from caching the service worker endpoints.
