### ISSUE TITLE
Displaying an offline page if the user is not connected to the Internet

### ISSUE THREAD

**Issue by Kuldas** [xwp/pwa-wp#703]
Hello, 

I would like to ask if it is possible to use a filter or action to show a user a simple page (like offline.html) if they are not connected to the internet?

**Comment by thelovekesh** [comment]
Hi @Kuldas,
This functionality is already there in the PWA plugin. You can try switching network status in the DevTools > Network tab and then explore your website. 
During offline browsing, if any page is not cached then you will visit the offline page.
![image](https://user-images.githubusercontent.com/54371619/154525157-d30bdc64-0414-4e69-89ad-cfe8bf1e889b.png)

For more information please visit [this](https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker#offline--500-error-handling) topic in the wiki.

**Comment by westonruter** [comment]
I've just updated the wiki to also link the [PWA Offline Template](https://gist.github.com/westonruter/900611f075374c5468ea492f23ad4810#file-pwa-offline-template-php) example which shows how you can supply the offline template via a plugin instead of requiring that you add it by adding an `offline.php` to your theme.
