### ISSUE TITLE
Any insight on when this will become core?

### ISSUE THREAD

**Issue by hirasso** [xwp/pwa-wp#931]
Hi there, love this feature plugin! Is there any information available if and when it will be proposed and merged into WordPress core?

**Comment by hirasso** [comment]
Ah, just found https://github.com/GoogleChromeLabs/pwa-wp/issues/884

...closing this

**Comment by nickchomey** [comment]
@hirasso I strongly suspect that it will never happen. I tried to initiate an effort for this and not only was there no interest, but the lead dev was actively against any such effort. I've carried on to design my own PWA which is considerably more performant than this plugin because it doesn't have to hook into a bunch of places. Also, if I recall correctly, it dynamically regenerates the service worker on each page load via AJAX, or something like that - it was a very unpleasant experience.

I'd recommend doing some custom work of your own, perhaps using one of the other standalone PWA plugins as a starting point (though, they are all extremely limited themselves...)

Feel free to check out the Performance team Slack chat log to make up your own mind about this though: https://make.wordpress.org/core/2022/11/29/performance-team-meeting-summary-29-november-2022/

**Comment by westonruter** [comment]
@nickchomey I'm not against it. It's just I don't think the case has been made yet. Pushing for something to be part of core before the case is strong enough will only cause headaches and technical debt down the road. One alternative in the short term is it could become a "[canonical plugin](https://make.wordpress.org/core/2022/09/11/canonical-plugins-revisited/)".

**Comment by nickchomey** [comment]
I never pushed for it to get into core.... I pushed - both in #884 (literally look at the issue's title!) and in the Performance Team Slack - to have a **_discussion_** about what needs to be done (an assessment of obstacles, opportunities, outstanding tasks, etc...) in order for it to perhaps get into core (or become a canonical plugin)  someday. However, not a single constructive word was or has been shared in either place (quite the opposite, in fact, as this thread continues to show), thus all of my enthusiasm to contribute to was rapidly quenched. 

Evidently this is not a priority for anyone, which is completely fine - I'd never presume to know/dictate what people's priorities should be in open-source. But I hope someday it will be, because PWAs have immense potential.

**Comment by hirasso** [comment]
I totally understand. I think the concept of PWAs is a bit unintuitive for many - it's not an easy to grasp "one thing fits all" but rather a collection of technologies that is a bit hard to wrap one's head around.

I also think that Apple's reluctance to allow other browsers then webkit on iOS is a big speed bump for bigger adaption of PWAs. And all that just to protect their App Store...

Hopefully this will change sometime in the future, when they finally open up their platform...

**Comment by nickchomey** [comment]
> I think the concept of PWAs is a bit unintuitive for many - it's not an easy to grasp "one thing fits all" but rather a collection of technologies that is a bit hard to wrap one's head around.

This is the entire point of WordPress... NONE of this is intuitive/accessible for anyone, but WP makes it so. It should do the same for PWAs.

> I also think that Apple's reluctance to allow other browsers then webkit on iOS is a big speed bump for bigger adaption of PWAs. And all that just to protect their App Store...

As I mentioned in the Slack thread in response to this very pushback ("why bother when Apple hates PWAs?!") - this is no reason not to move forward with this. Moreover, if 40+% of the web (WordPress) had a robust PWA mechanism - with the backing of Google-sponsored devs whose task was presumably to make this happen... - I think Apple would start to change their tune. 

But, that's clearly not going to happen any time soon. Again, I recommend you look into making your own PWA implementation

p.s. Apple will be adding Push Notifications (which is one of the only meaningful PWA technologies missing from Safari) VERY soon. 
* https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/
* https://kevinbasset.medium.com/sending-push-notifications-with-safari-16-on-macos-ventura-f099dc0e7274
